[package]
name = "optagentnet"
version = "0.1.0"
authors = ["bhaskar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.1"
rand = "0.7.3"
